version: "3.3"

services:
  traefik:
    image: traefik:v2.1.3
    restart: always
    container_name: traefik
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy
      - --entrypoints.web.address=:80
      - --entrypoints.web-secured.address=:443
      - --certificatesresolvers.mytlschallenge.acme.httpChallenge.entrypoint=web
      - --certificatesresolvers.mytlschallenge.acme.email=${EMAIL}
      - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json
    volumes:
      - traefik_le:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.api.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.api.service=api@internal

networks:
  proxy:
    external: true

volumes:
  traefik_le:
